### ISSUE TITLE
Custom framework name

### ISSUE THREAD

**Issue by mksmdvdff** [icerockdev/mobile-multiplatform-gradle-plugin#9]
Sometimes it may be needed to use some multiplatform libraries in iOS Application, and, as I understand, Swift doesn't allow us to import some frameworks with the same name. It will be useful to add an optional parameter with the default value to `setupFramework` method.

**Comment by Alex009** [comment]
yes, we can add it.
but recommended way to use multiplatform libraries is one multiplatform framework, which includes all other mpp libs. for example - https://github.com/icerockdev/moko-template/blob/master/mpp-library/build.gradle.kts here one framework, but it export other libraries to own header.

you can send PR with optional param in setupFramework, or wait while we do it self

**Comment by Alex009** [comment]
merged, will be in 0.6.0 release
